# Generated by Django 4.2.3 on 2024-11-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='meal',
            new_name='meal_type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='type',
        ),
        migrations.AddField(
            model_name='diet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(default='運動未定義', max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='intensity',
            field=models.CharField(default='中', max_length=10),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
